
package com.zhys.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISmsService", targetNamespace = "http://api.gongniu.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISmsService {


    /**
     * 
     * @param systemId
     * @param sendInfo
     * @return
     *     returns com.zhys.ws.ApiResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendSms", targetNamespace = "http://api.gongniu.cn/", className = "com.zhys.ws.SendSms")
    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://api.gongniu.cn/", className = "com.zhys.ws.SendSmsResponse")
    public ApiResult sendSms(
            @WebParam(name = "systemId", targetNamespace = "")
                    String systemId,
            @WebParam(name = "sendInfo", targetNamespace = "")
                    String sendInfo);

}
