
package com.zhys.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmsServiceImplService", targetNamespace = "http://service.sms.gongniu.cn/", wsdlLocation = "http://172.16.0.67:8002/ws/sms?wsdl")
public class SmsServiceImplService
    extends Service
{

    private final static URL SMSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SMSSERVICEIMPLSERVICE_QNAME = new QName("http://service.sms.gongniu.cn/", "SmsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.0.67:8002/ws/sms?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SMSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SmsServiceImplService() {
        super(__getWsdlLocation(), SMSSERVICEIMPLSERVICE_QNAME);
    }

    public SmsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSSERVICEIMPLSERVICE_QNAME, features);
    }

    public SmsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SMSSERVICEIMPLSERVICE_QNAME);
    }

    public SmsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSSERVICEIMPLSERVICE_QNAME, features);
    }

    public SmsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISmsService
     */
    @WebEndpoint(name = "SmsServiceImplPort")
    public ISmsService getSmsServiceImplPort() {
        return super.getPort(new QName("http://service.sms.gongniu.cn/", "SmsServiceImplPort"), ISmsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISmsService
     */
    @WebEndpoint(name = "SmsServiceImplPort")
    public ISmsService getSmsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sms.gongniu.cn/", "SmsServiceImplPort"), ISmsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SMSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SMSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
